language: go
go:
  - "1.13"

before_install:
  - go get -t -v ./...

script:
  - go vet ./...
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
